name: emobeats
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.jpg
    - assets/images/anxious.jpg
    - assets/images/audiomack.jpg
    - assets/images/emobeats.jpg
    - assets/images/emologo.jpg
    - assets/images/energetic.jpg
    - assets/images/grateful.jpg
    - assets/images/Happy.jpg
    - assets/images/heartbroken.jpg
    - assets/images/openailogo.png
    - assets/images/relaxed.jpg
    - assets/images/romance.jpg
    - assets/images/spotify.png

